# Generated by Django 5.1.2 on 2024-12-07 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_merge_20241204_1655'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(related_name='student_subjects', through='subjects.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
