# Generated by Django 5.1.2 on 2025-01-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_user_delete_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/noavatar.png', null=True, upload_to='avatars/'),
        ),
    ]
